export const songs = [
  {
    id: 1,
    title: 'Mojo Pin',
    artist: 'Jeff Buckley',
    album: 'Grace',
    artwork: require('../../assets/images/img_01.jpg'),
    duration: 343,
    url: require('../../assets/audio/01_Mojo-Pin.mp3'),
  },
  {
    id: 2,
    title: 'Grace',
    artist: 'Jeff Buckley',
    album: 'Grace',
    artwork: require('../../assets/images/img_02.jpg'),
    duration: 324,
    url: require('../../assets/audio/02_Grace.mp3'),
  },
  {
    id: 3,
    title: 'Last Goodbye',
    artist: 'Jeff Buckley',
    album: 'Grace',
    artwork: require('../../assets/images/img_03.jpg'),
    duration: 277,
    url: require('../../assets/audio/03_Last-Goodbye.mp3'),
  },
  {
    id: 4,
    title: 'Lilac Wine',
    artist: 'Jeff Buckley',
    album: 'Grace',
    artwork: require('../../assets/images/img_04.jpg'),
    duration: 274,
    url: require('../../assets/audio/04_Lilac-Wine.mp3'),
  },
  {
    id: 5,
    title: 'So Real',
    artist: 'Jeff Buckley',
    album: 'Grace',
    artwork: require('../../assets/images/img_05.jpg'),
    duration: 285,
    url: require('../../assets/audio/05_So-Real.mp3'),
  },
  {
    id: 6,
    title: 'Hallelujah',
    artist: 'Jeff Buckley',
    album: 'Grace',
    artwork: require('../../assets/images/img_06.jpg'),
    duration: 415,
    url: require('../../assets/audio/06_Hallelujah.mp3'),
  },

  {
    id: 7,
    title: "Lover, You Should've Come Over",
    artist: 'Jeff Buckley',
    album: 'Grace',
    artwork: require('../../assets/images/img_07.jpg'),
    duration: 405,
    url: require('../../assets/audio/07_Lover-You-Shouldve-Come-Over.mp3'),
  },
  {
    id: 8,
    title: 'Corpus Christi Carol',
    artist: 'Jeff Buckley',
    album: 'Grace',
    artwork: require('../../assets/images/img_08.jpg'),
    duration: 178,
    url: require('../../assets/audio/08_Corpus-Christi-Carol.mp3'),
  },
  {
    id: 9,
    title: 'Eternal Life',
    artist: 'Jeff Buckley',
    album: 'Grace',
    artwork: require('../../assets/images/img_09.jpg'),
    duration: 294,
    url: require('../../assets/audio/09_Eternal-Life.mp3'),
  },
  {
    id: 10,
    title: 'Dream Brother',
    artist: 'Jeff Buckley',
    album: 'Grace',
    artwork: require('../../assets/images/img_10.jpg'),
    duration: 326,
    url: require('../../assets/audio/10_Dream-Brother.mp3'),
  },
];
